
"use strict";
window.addEventListener("DOMContentLoaded", () => {
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => Array.from(document.querySelectorAll(s));
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const irand = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;
  const dist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  const css = (v) => getComputedStyle(document.body).getPropertyValue(v).trim();

  let activeGame = "void";
  const keys = new Set();

  function showSection(id) {
    $$(".section").forEach((sec) => sec.classList.toggle("active", sec.id === id));
    $$(".nav-btn").forEach((btn) => btn.classList.toggle("active", btn.dataset.target === id));
    if (id !== "games") activeGame = null;
    if (id === "games" && !activeGame) activeGame = document.querySelector(".game-tab.active")?.dataset.game || "void";
  }
  function showGame(id) {
    activeGame = id;
    $$(".game-tab").forEach((btn) => btn.classList.toggle("active", btn.dataset.game === id));
    $$(".game-screen").forEach((screen) => screen.classList.toggle("active", screen.id === id));
  }
  $$('[data-target]').forEach((btn) => btn.addEventListener("click", () => { showSection(btn.dataset.target); if (btn.dataset.gameJump) showGame(btn.dataset.gameJump); }));
  $$(".game-tab").forEach((btn) => btn.addEventListener("click", () => showGame(btn.dataset.game)));
  $("#themeToggleBtn").addEventListener("click", () => document.body.classList.toggle("theme-light"));
  $("#rulesToggleBtn").addEventListener("click", () => $("#rulesBlock").classList.toggle("hidden"));
  $("#feedbackForm").addEventListener("submit", (e) => { e.preventDefault(); const name = $("#fbName").value.trim() || "Player"; $("#feedbackThanks").textContent = `Thanks, ${name}. Feedback saved locally for this demo.`; $("#feedbackThanks").classList.remove("hidden"); e.currentTarget.reset(); });
  window.addEventListener("keydown", (e) => { const t = e.target?.tagName?.toLowerCase(); if (["input", "textarea", "select"].includes(t)) return; keys.add(e.key.toLowerCase()); if (["arrowup","arrowdown","arrowleft","arrowright"," "].includes(e.key.toLowerCase())) e.preventDefault(); if (activeGame === "maze") mazeKey(e.key.toLowerCase()); });
  window.addEventListener("keyup", (e) => keys.delete(e.key.toLowerCase()));

  /* VOID SALVAGE */
  const vC = $("#voidCanvas"), vtx = vC.getContext("2d");
  let voidRun;
  function resetVoid() { voidRun = { running:false, wave:1, hp:100, scrap:0, score:0, speed:3.2, damage:16, player:{x:vC.width/2,y:vC.height/2,r:14}, drones:[], crystals:[], mines:[], shots:[], last:0, spawn:0, fire:0 }; updateVoidHud(); drawVoid(); $("#voidMsg").textContent="Press Start Run."; }
  function startVoid() { if (!voidRun) resetVoid(); if (voidRun.running) return; voidRun.running = true; voidRun.last = performance.now(); $("#voidMsg").textContent="Collect crystals and survive."; requestAnimationFrame(voidLoop); }
  function spawnVoidWave() { const v=voidRun; for(let i=0;i<3+v.wave;i++) v.drones.push({x:Math.random()*vC.width,y:Math.random()*vC.height,r:12,hp:24+v.wave*7,spd:1+v.wave*.08}); for(let i=0;i<5;i++) v.crystals.push({x:irand(30,vC.width-30),y:irand(30,vC.height-30),r:8}); for(let i=0;i<Math.min(8,1+Math.floor(v.wave/2));i++) v.mines.push({x:irand(30,vC.width-30),y:irand(30,vC.height-30),r:12}); v.wave++; }
  function voidLoop(t){ const v=voidRun; if(!v?.running) return; const dt=Math.min(.033,(t-v.last)/1000||.016); v.last=t; let dx=0,dy=0; if(keys.has("a")||keys.has("arrowleft"))dx--; if(keys.has("d")||keys.has("arrowright"))dx++; if(keys.has("w")||keys.has("arrowup"))dy--; if(keys.has("s")||keys.has("arrowdown"))dy++; const len=Math.hypot(dx,dy)||1; v.player.x=clamp(v.player.x+dx/len*v.speed*80*dt,16,vC.width-16); v.player.y=clamp(v.player.y+dy/len*v.speed*80*dt,16,vC.height-16); if(v.drones.length===0) spawnVoidWave(); v.fire-=dt; if(v.fire<=0&&v.drones.length){ const target=v.drones.slice().sort((a,b)=>dist(v.player,a)-dist(v.player,b))[0]; const a=Math.atan2(target.y-v.player.y,target.x-v.player.x); v.shots.push({x:v.player.x,y:v.player.y,vx:Math.cos(a)*360,vy:Math.sin(a)*360,life:1}); v.fire=.22; }
    v.shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;}); v.shots=v.shots.filter(s=>s.life>0&&s.x>0&&s.y>0&&s.x<vC.width&&s.y<vC.height);
    v.drones.forEach(d=>{const a=Math.atan2(v.player.y-d.y,v.player.x-d.x);d.x+=Math.cos(a)*d.spd*44*dt;d.y+=Math.sin(a)*d.spd*44*dt;if(dist(d,v.player)<d.r+v.player.r){v.hp-=18*dt;}});
    v.shots.forEach(s=>v.drones.forEach(d=>{if(dist(s,d)<d.r+3){d.hp-=v.damage;s.life=0;}}));
    v.drones=v.drones.filter(d=>{if(d.hp<=0){v.scrap+=6;v.score+=20;return false}return true});
    v.crystals=v.crystals.filter(c=>{if(dist(c,v.player)<c.r+v.player.r){v.scrap+=5;v.score+=10;return false}return true});
    v.mines=v.mines.filter(m=>{if(dist(m,v.player)<m.r+v.player.r){v.hp-=20;return false}return true});
    if(v.hp<=0){v.running=false;$("#voidMsg").textContent=`Run ended. Score ${v.score}.`;}
    updateVoidHud(); drawVoid(); if(v.running)requestAnimationFrame(voidLoop); }
  function updateVoidHud(){ if(!voidRun)return; $("#voidWave").textContent=voidRun.wave; $("#voidHp").textContent=Math.max(0,Math.floor(voidRun.hp)); $("#voidScrap").textContent=voidRun.scrap; $("#voidScore").textContent=voidRun.score; }
  function drawVoid(){ const v=voidRun;if(!v)return;vtx.clearRect(0,0,vC.width,vC.height);vtx.fillStyle="#050713";vtx.fillRect(0,0,vC.width,vC.height);vtx.fillStyle="rgba(255,255,255,.12)";for(let i=0;i<80;i++)vtx.fillRect((i*83)%vC.width,(i*47)%vC.height,2,2);v.crystals.forEach(c=>{vtx.fillStyle=css("--accent");vtx.beginPath();vtx.arc(c.x,c.y,c.r,0,Math.PI*2);vtx.fill()});v.mines.forEach(m=>{vtx.strokeStyle=css("--warn");vtx.beginPath();vtx.arc(m.x,m.y,m.r,0,Math.PI*2);vtx.stroke()});v.drones.forEach(d=>{vtx.fillStyle=css("--bad");vtx.beginPath();vtx.arc(d.x,d.y,d.r,0,Math.PI*2);vtx.fill()});v.shots.forEach(s=>{vtx.fillStyle=css("--warn");vtx.fillRect(s.x-2,s.y-2,4,4)});vtx.fillStyle=css("--accent");vtx.beginPath();vtx.arc(v.player.x,v.player.y,v.player.r,0,Math.PI*2);vtx.fill(); }
  $$("[data-void-up]").forEach(b=>b.addEventListener("click",()=>{const v=voidRun;if(!v)return;const up=b.dataset.voidUp;if(up==="speed"&&v.scrap>=30){v.scrap-=30;v.speed+=.35}if(up==="damage"&&v.scrap>=35){v.scrap-=35;v.damage+=6}if(up==="repair"&&v.scrap>=25){v.scrap-=25;v.hp=clamp(v.hp+35,0,100)}updateVoidHud()}));
  $("#voidStartBtn").addEventListener("click",startVoid); $("#voidResetBtn").addEventListener("click",resetVoid);

  /* RUNE GAMBIT */
  let rune; const runeTypes=["strike","guard","spark","heal","gold"]; const runeIcon={strike:"ATK",guard:"DEF",spark:"ARC",heal:"HP",gold:"G$"};
  function resetRune(){rune={round:1,hp:40,maxHp:40,gold:0,rolls:3,dice:Array.from({length:5},()=>({type:"strike",locked:false})),enemy:null};newRuneEnemy();rollRunes(true);updateRune();$("#runeMsg").textContent="Lock dice, roll, then resolve.";}
  function newRuneEnemy(){const hp=32+rune.round*8;rune.enemy={name:["Gutter Imp","Glass Knight","Static Wraith","Debt Ogre"][irand(0,3)],hp,max:hp,attack:7+rune.round*2};}
  function rollRunes(force=false){if(!rune)return;if(rune.rolls<=0&&!force)return;rune.dice.forEach(d=>{if(!d.locked||force)d.type=runeTypes[irand(0,runeTypes.length-1)]});if(!force)rune.rolls--;drawRunes();updateRune();}
  function resolveRunes(){if(!rune?.enemy)return;const counts={};rune.dice.forEach(d=>counts[d.type]=(counts[d.type]||0)+1);let dmg=(counts.strike||0)*7+(counts.spark||0)*4,block=(counts.guard||0)*5;if((counts.spark||0)>=3)dmg+=18;if((counts.strike||0)>=3)dmg+=15;if(counts.heal)rune.hp=clamp(rune.hp+counts.heal*4,0,rune.maxHp);if(counts.gold)rune.gold+=counts.gold*3;rune.enemy.hp-=dmg;let text=`Dealt ${dmg}, blocked ${block}.`;if(rune.enemy.hp<=0){rune.gold+=15+rune.round*2;rune.round++;rune.rolls=3;rune.dice.forEach(d=>d.locked=false);newRuneEnemy();rollRunes(true);text+=" Enemy defeated."}else{const hit=Math.max(0,rune.enemy.attack-block);rune.hp-=hit;text+=` Enemy hit for ${hit}.`;rune.rolls=3;rune.dice.forEach(d=>d.locked=false);rollRunes(true)}if(rune.hp<=0){text=`Defeated on round ${rune.round}. Press New Battle.`}$("#runeMsg").textContent=text;updateRune();drawRunes();}
  function drawRunes(){const grid=$("#runeGrid");grid.innerHTML="";if(!rune)return;rune.dice.forEach((d,i)=>{const b=document.createElement("button");b.className="rune"+(d.locked?" locked":"");b.innerHTML=`${runeIcon[d.type]}<small>${d.type}</small>`;b.addEventListener("click",()=>{d.locked=!d.locked;drawRunes()});grid.appendChild(b)});}
  function updateRune(){if(!rune)return;$("#runeRound").textContent=rune.round;$("#runeHp").textContent=Math.max(0,rune.hp);$("#runeEnemyHp").textContent=Math.max(0,Math.ceil(rune.enemy.hp));$("#runeGold").textContent=rune.gold;$("#runeEnemy").textContent=`${rune.enemy.name}: ${Math.ceil(rune.enemy.hp)}/${rune.enemy.max} HP. Attack ${rune.enemy.attack}. Rolls ${rune.rolls}.`;}
  $("#runeStartBtn").addEventListener("click",resetRune);$("#runeRollBtn").addEventListener("click",()=>rollRunes(false));$("#runeResolveBtn").addEventListener("click",resolveRunes);

  /* NEON LABYRINTH */
  const mC=$("#mazeCanvas"), m=mC.getContext("2d"); let maze,mazeProg; const portalColors=["orange","purple","cyan","green","pink"],portalPaint={orange:"#ff9f1c",purple:"#9b5cff",cyan:"#00e5ff",green:"#48ff9b",pink:"#ff5cc8"};
  function resetMaze(){mazeProg={rooms:0,lives:2,maxLives:2,delay:1,phase:0,radar:0};startMazeRoom(1)}
  function startMazeRoom(level){const size=level>=16?23:level>=8?21:19;maze={level,size,tile:mC.width/size,grid:[],player:{x:1,y:1},start:{x:1,y:1},exit:{x:size-2,y:size-2},keys:[],got:0,need:Math.min(5,2+Math.floor(level/5)),hunters:[],hazards:[],portals:[],counter:0,active:true};genMaze();updateMazeHud();drawMaze();$("#mazeMsg").textContent=`Room ${level}: collect keys and escape.`;}
  function genMaze(){const z=maze;z.grid=Array.from({length:z.size},()=>Array(z.size).fill(1));function carve(x,y){z.grid[y][x]=0;[[2,0],[-2,0],[0,2],[0,-2]].sort(()=>Math.random()-.5).forEach(([dx,dy])=>{const nx=x+dx,ny=y+dy;if(nx>0&&ny>0&&nx<z.size-1&&ny<z.size-1&&z.grid[ny][nx]){z.grid[y+dy/2][x+dx/2]=0;carve(nx,ny)}})}carve(1,1);for(let i=0;i<z.size*3;i++){const x=irand(1,z.size-2),y=irand(1,z.size-2);if(Math.random()<.55)z.grid[y][x]=0}z.exit={x:z.size-2,y:z.size-2};z.grid[z.exit.y][z.exit.x]=0;let opens=listMazeOpen().filter(p=>pathMaze(z.start,p).length>8);z.keys=[];while(z.keys.length<z.need&&opens.length){const p=opens.splice(irand(0,opens.length-1),1)[0];if(!nearAny(p,[z.start,z.exit,...z.keys],4))z.keys.push(p)}const hCount=Math.min(6,1+Math.floor(mazeProg.rooms/10));z.hunters=[];opens=listMazeOpen().filter(p=>pathMaze(z.start,p).length>10&&!nearAny(p,[z.start,z.exit,...z.keys],5));for(let i=0;i<hCount;i++){const p=opens.splice(irand(0,Math.max(0,opens.length-1)),1)[0]||{x:z.size-2,y:1};z.hunters.push({...p,spawn:{...p},id:i})}z.portals=[];const pairs=Math.min(portalColors.length,Math.floor(z.level/15));opens=listMazeOpen().filter(p=>!nearAny(p,[z.start,z.exit,...z.keys,...z.hunters],3));for(let i=0;i<pairs;i++){const a=opens.shift(),b=opens.find(p=>a&&Math.abs(p.x-a.x)+Math.abs(p.y-a.y)>8);if(a&&b){opens.splice(opens.indexOf(b),1);z.portals.push({...a,color:portalColors[i]},{...b,color:portalColors[i]})}}z.hazards=[];opens=listMazeOpen().filter(p=>!nearAny(p,[z.start,z.exit,...z.keys,...z.hunters,...z.portals],2));const count=Math.min(28,z.level*2);for(let i=0;i<count&&opens.length;i++){const p=opens.splice(irand(0,opens.length-1),1)[0];z.hazards.push({...p,type:["trap","spike","alarm","rift"][irand(0,3)]})}}
  function listMazeOpen(){const out=[];for(let y=1;y<maze.size-1;y++)for(let x=1;x<maze.size-1;x++)if(maze.grid[y][x]===0)out.push({x,y});return out}function canMaze(x,y){return maze&&maze.grid[y]?.[x]===0}function nearAny(p,l,r){return l.some(q=>q&&Math.abs(q.x-p.x)+Math.abs(q.y-p.y)<=r)}
  function pathMaze(a,b){const q=[a],seen=new Set([`${a.x},${a.y}`]),prev=new Map();for(let i=0;i<q.length;i++){const p=q[i];if(p.x===b.x&&p.y===b.y)break;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{const nx=p.x+dx,ny=p.y+dy,k=`${nx},${ny}`;if(canMaze(nx,ny)&&!seen.has(k)){seen.add(k);prev.set(k,p);q.push({x:nx,y:ny})}})}if(!seen.has(`${b.x},${b.y}`))return[];const path=[];let cur=b;while(cur){path.push(cur);cur=prev.get(`${cur.x},${cur.y}`)}return path.reverse()}
  function mazeKey(k){if(!maze?.active)return;let dx=0,dy=0;if(k==="a"||k==="arrowleft")dx=-1;if(k==="d"||k==="arrowright")dx=1;if(k==="w"||k==="arrowup")dy=-1;if(k==="s"||k==="arrowdown")dy=1;if(!dx&&!dy)return;const nx=maze.player.x+dx,ny=maze.player.y+dy;if(!canMaze(nx,ny)){if(mazeProg.phase>0&&nx>0&&ny>0&&nx<maze.size-1&&ny<maze.size-1){maze.grid[ny][nx]=0;mazeProg.phase--}else return}maze.player={x:nx,y:ny};useMazePortal(maze.player);maze.keys=maze.keys.filter(k=>{if(k.x===maze.player.x&&k.y===maze.player.y){maze.got++;return false}return true});const hz=maze.hazards.find(h=>h.x===maze.player.x&&h.y===maze.player.y);if(hz){maze.hazards=maze.hazards.filter(h=>h!==hz);if(hz.type==="rift")maze.player={...maze.start};else if(hz.type==="alarm")moveHunters(2);else hurtMaze(`${hz.type} hit.`)}if(maze.player.x===maze.exit.x&&maze.player.y===maze.exit.y&&maze.got>=maze.need){maze.active=false;mazeProg.rooms++;if(mazeProg.rooms%5===0){$("#mazeUpgradeShop").classList.remove("hidden");$("#mazeMsg").textContent="Choose an upgrade."}else setTimeout(()=>startMazeRoom(maze.level+1),500)}maze.counter++;if(maze.counter>=mazeProg.delay){maze.counter=0;moveHunters(1)}checkMazeCatch();updateMazeHud();drawMaze()}
  function moveHunters(steps){for(let s=0;s<steps;s++)for(const h of maze.hunters){const opts=[h,...[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:h.x+dx,y:h.y+dy})).filter(p=>canMaze(p.x,p.y))];let best=opts[0],score=1e9;const obj=maze.got>=maze.need?maze.exit:(maze.keys[0]||maze.exit);for(const p of opts){let sc=pathMaze(p,maze.player).length*7+pathMaze(p,obj).length*2+Math.random();if(sc<score){score=sc;best=p}}h.x=best.x;h.y=best.y;useMazePortal(h)}}
  function useMazePortal(e){const p=maze.portals.find(q=>q.x===e.x&&q.y===e.y);if(!p)return;const other=maze.portals.find(q=>q.color===p.color&&(q.x!==p.x||q.y!==p.y));if(other){e.x=other.x;e.y=other.y}}
  function checkMazeCatch(){if(maze.hunters.some(h=>h.x===maze.player.x&&h.y===maze.player.y))hurtMaze("Hunter caught you.")}function hurtMaze(msg){mazeProg.lives--;maze.player={...maze.start};maze.hunters.forEach(h=>{h.x=h.spawn.x;h.y=h.spawn.y});$("#mazeMsg").textContent=msg;if(mazeProg.lives<=0){maze.active=false;$("#mazeMsg").textContent=`Run ended after ${mazeProg.rooms} rooms.`}}
  function updateMazeHud(){if(!maze)return;$("#mazeLevel").textContent=maze.level;$("#mazeKeys").textContent=`${maze.got}/${maze.need}`;$("#mazeLives").textContent=mazeProg.lives;$("#mazeHunters").textContent=maze.hunters.length;$("#mazeHazards").textContent=maze.hazards.length;$("#mazeRooms").textContent=mazeProg.rooms}
  function drawMaze(){if(!maze)return;const t=maze.tile;m.clearRect(0,0,mC.width,mC.height);for(let y=0;y<maze.size;y++)for(let x=0;x<maze.size;x++){m.fillStyle=maze.grid[y][x]?"#141a30":"rgba(255,255,255,.05)";m.fillRect(x*t,y*t,t-1,t-1)}maze.portals.forEach(p=>{m.strokeStyle=portalPaint[p.color];m.lineWidth=3;m.beginPath();m.arc((p.x+.5)*t,(p.y+.5)*t,t*.28,0,Math.PI*2);m.stroke()});maze.hazards.forEach(h=>{m.fillStyle=h.type==="spike"?css("--bad"):h.type==="alarm"?css("--warn"):h.type==="rift"?"#00e5ff":css("--accent2");m.fillRect(h.x*t+t*.3,h.y*t+t*.3,t*.4,t*.4)});m.fillStyle=maze.got>=maze.need?css("--good"):css("--muted");m.fillRect(maze.exit.x*t+5,maze.exit.y*t+5,t-10,t-10);m.fillStyle=css("--warn");maze.keys.forEach(k=>{m.beginPath();m.arc((k.x+.5)*t,(k.y+.5)*t,t*.22,0,Math.PI*2);m.fill()});m.fillStyle=css("--bad");maze.hunters.forEach(h=>{m.beginPath();m.arc((h.x+.5)*t,(h.y+.5)*t,t*.3,0,Math.PI*2);m.fill()});m.fillStyle=css("--accent");m.beginPath();m.arc((maze.player.x+.5)*t,(maze.player.y+.5)*t,t*.32,0,Math.PI*2);m.fill()}
  $("#mazeStartBtn").addEventListener("click",()=>resetMaze());$("#mazeResetBtn").addEventListener("click",()=>resetMaze());$$('[data-maze-up]').forEach(b=>b.addEventListener("click",()=>{if(b.dataset.mazeUp==="life"){mazeProg.maxLives++;mazeProg.lives=mazeProg.maxLives}if(b.dataset.mazeUp==="slow")mazeProg.delay=clamp(mazeProg.delay+1,1,4);if(b.dataset.mazeUp==="phase")mazeProg.phase+=2;if(b.dataset.mazeUp==="radar")mazeProg.radar+=3;$("#mazeUpgradeShop").classList.add("hidden");startMazeRoom(maze.level+1)}));

  /* GLITCH GARDEN */
  const gC=$("#gardenCanvas"), g=gC.getContext("2d"); const GC=18,GR=12,GT=40,SPAWN={x:0,y:6},PATH_START={x:1,y:6},BASE={x:17,y:6}; let garden,selectedTool="dig",selectedArea=1,areaUnlocked=[true,false,false];
  const tools={dig:{kind:"dig",gain:4},pulse:{kind:"tower",cost:55,range:112,rate:.58,dmg:13,color:"#00f5c4"},frost:{kind:"tower",cost:75,range:105,rate:.85,dmg:7,color:"#8be9ff"},rail:{kind:"tower",cost:115,range:170,rate:1.45,dmg:34,color:"#ffd166"},acid:{kind:"tower",cost:90,range:96,rate:.72,dmg:8,color:"#48ff9b"},beacon:{kind:"tower",cost:120,range:190,rate:1.05,dmg:24,color:"#ff7bd5"},tar:{kind:"trap",cost:45,color:"#6b5cff"},spikes:{kind:"trap",cost:40,color:"#c0c0c0"},emp:{kind:"trap",cost:85,color:"#00e5ff"},flame:{kind:"trap",cost:70,color:"#ff9f1c"},crusher:{kind:"trap",cost:105,color:"#ff3864"}};
  const enemyTypes=[{id:"bit",hp:30,speed:28,reward:8,color:"#ff2d78",unlock:1,tags:[]},{id:"run",hp:24,speed:46,reward:9,color:"#ffd166",unlock:4,tags:["fast"]},{id:"shell",hp:72,speed:20,reward:14,color:"#b8b8ff",unlock:8,tags:["armored"]},{id:"wisp",hp:46,speed:34,reward:13,color:"#00e5ff",unlock:12,tags:["flying"]},{id:"regen",hp:86,speed:24,reward:16,color:"#48ff9b",unlock:18,tags:["regen"]},{id:"shield",hp:96,speed:23,reward:19,color:"#7c3aed",unlock:25,tags:["shielded"]},{id:"phantom",hp:145,speed:33,reward:31,color:"#f0f0ff",unlock:60,tags:["stealth"]}];
  function key(x,y){return `${x},${y}`}function validGarden(x,y){return x>=0&&y>=0&&x<GC&&y<GR}function isPath(x,y){return garden.dug.has(key(x,y))}function isTower(x,y){return garden.towers.some(t=>t.x===x&&t.y===y)}function isTrap(x,y){return garden.traps.some(t=>t.x===x&&t.y===y)}function gardenCenter(p){return{x:p.x*GT+GT/2,y:p.y*GT+GT/2}}function endpoint(){return garden.dugOrder[garden.dugOrder.length-1]||PATH_START}
  function areaData(area){const water=new Set(),jam=new Set();if(area>=2)[[5,2],[5,3],[5,4],[5,8],[5,9],[5,10],[10,1],[10,2],[10,9],[10,10],[13,4],[13,7]].forEach(a=>water.add(key(...a)));if(area>=3){[[3,3],[3,4],[4,3],[14,8],[14,9],[15,8],[8,5],[8,6],[9,5],[9,6]].forEach(a=>jam.add(key(...a)));[[7,1],[7,10],[12,2],[12,9]].forEach(a=>water.add(key(...a)))}return{water,jam}}
  function resetGarden(){const a=areaData(selectedArea);garden={running:false,wave:1,money:130,core:20,kills:0,area:selectedArea,dug:new Set([key(PATH_START.x,PATH_START.y)]),dugOrder:[{...PATH_START}],route:[SPAWN,{...PATH_START}],pathReady:false,towers:[],traps:[],enemies:[],shots:[],spawnQueue:[],spawnTimer:0,last:0,water:a.water,jam:a.jam,bossOffered:false,endless:false};$("#gardenBossChoice").classList.add("hidden");selectedTool="dig";updateGardenButtons();updateGardenHud();drawGarden();$("#gardenMsg").textContent="Select Remove Block, then click one highlighted block at the front of the path."}
  function recomputeGarden(){garden.route=[SPAWN,...garden.dugOrder];const last=endpoint();garden.pathReady=last.x===BASE.x&&last.y===BASE.y;return garden.pathReady}
  function validNextTiles(){if(!garden||garden.running||garden.pathReady)return[];const e=endpoint(),old=garden.dugOrder.slice(0,-1);return [[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:e.x+dx,y:e.y+dy})).filter(p=>validGarden(p.x,p.y)&&!(p.x===SPAWN.x&&p.y===SPAWN.y)&&!garden.water.has(key(p.x,p.y))&&!isPath(p.x,p.y)&&!isTower(p.x,p.y)&&!isTrap(p.x,p.y)&&!old.some(q=>Math.abs(q.x-p.x)+Math.abs(q.y-p.y)===1))}
  function digGarden(x,y){if(garden.running)return;if(!validGarden(x,y))return;if(garden.pathReady){msgG("Path is connected. Start the wave or reset for a new route.");return}const valid=validNextTiles().some(p=>p.x===x&&p.y===y);if(!valid){msgG("Only the highlighted block at the front of the path can be removed.");return}garden.dug.add(key(x,y));garden.dugOrder.push({x,y});garden.money+=4;const done=recomputeGarden();msgG(done?"Base connected. Place towers/traps, then start the wave.":"Block removed. +4 money. Continue from the highlighted front.");updateGardenHud();drawGarden()}
  function placeGarden(x,y){const tool=tools[selectedTool];if(tool.kind==="dig")return digGarden(x,y);if(garden.running){msgG("Build between waves only.");return}if(!validGarden(x,y)||garden.water.has(key(x,y))){msgG("Blocked tile.");return}if(garden.money<tool.cost){msgG("Not enough money.");return}if(tool.kind==="tower"){if(isPath(x,y)||isTower(x,y)||x===SPAWN.x&&y===SPAWN.y||x===BASE.x&&y===BASE.y){msgG("Towers go off the path.");return}garden.money-=tool.cost;garden.towers.push({x,y,type:selectedTool,cool:0})}else{if(!isPath(x,y)||x===PATH_START.x&&y===PATH_START.y||x===BASE.x&&y===BASE.y||isTrap(x,y)){msgG("Traps go on path tiles, not starter/base.");return}garden.money-=tool.cost;garden.traps.push({x,y,type:selectedTool,cool:0})}updateGardenHud();drawGarden()}
  function startGarden(){if(garden.running)return;if(!garden.pathReady){msgG("Extend the front of the path until it reaches the green base first.");return}garden.running=true;garden.last=performance.now();garden.spawnQueue=buildGWave(garden.wave);garden.spawnTimer=.25;garden.enemies=[];garden.shots=[];updateGardenButtons();msgG(garden.wave===100?"Boss wave started.":`Wave ${garden.wave} started.`);requestAnimationFrame(gardenLoop)}
  function buildGWave(w){const q=[],available=enemyTypes.filter(e=>e.unlock<=w),count=Math.min(70,7+Math.floor(w*1.25));for(let i=0;i<count;i++)q.push(makeGEnemy(available[irand(0,available.length-1)],w,false,false));if(w%10===0&&w!==100)q.push(makeGEnemy(available[irand(0,available.length-1)],w,true,false));if(w===100||w>100&&w%25===0)q.push(makeGEnemy({id:"boss",hp:240,speed:15,reward:650,color:"#ff3864",tags:["boss","armored","shielded","regen"]},w,false,true));return q}
  function makeGEnemy(type,w,mini,boss){const scale=1+(w-1)*.055+Math.pow(w,1.08)*.006,hp=(boss?4800:mini?type.hp*9:type.hp)*scale;return{hp,max:hp,shield:type.tags.includes("shielded")?hp*.3:0,speed:type.speed*(boss?.55:mini?.68:1),reward:boss?650:mini?110+w*3:Math.floor(type.reward+w*.55),color:type.color,tags:type.tags.slice(),seg:0,prog:0,x:gardenCenter(SPAWN).x,y:gardenCenter(SPAWN).y,slow:0,stun:0,burn:0,acid:0,revealed:0,mini,boss}}
  function gardenLoop(t){if(!garden.running)return;const dt=Math.min(.033,(t-garden.last)/1000||.016);garden.last=t;garden.spawnTimer-=dt;if(garden.spawnQueue.length&&garden.spawnTimer<=0){garden.enemies.push(garden.spawnQueue.shift());garden.spawnTimer=Math.max(.18,.75-garden.wave*.004)}garden.enemies.forEach(e=>updateGEnemy(e,dt));garden.towers.forEach(tw=>updateGTower(tw,dt));garden.traps.forEach(tr=>updateGTrap(tr,dt));garden.shots=garden.shots.filter(s=>(s.life-=dt)>0);garden.enemies=garden.enemies.filter(e=>{if(e.hp<=0){garden.kills++;garden.money+=e.reward;return false}if(e.reached){garden.core-=e.boss?8:e.mini?4:1;return false}return true});if(garden.core<=0){garden.running=false;msgG(`Core destroyed on wave ${garden.wave}.`);updateGardenButtons()}else if(!garden.spawnQueue.length&&!garden.enemies.length){clearGWave();return}updateGardenHud();drawGarden();if(garden.running)requestAnimationFrame(gardenLoop)}
  function updateGEnemy(e,dt){e.slow=Math.max(0,e.slow-dt);e.stun=Math.max(0,e.stun-dt);e.burn=Math.max(0,e.burn-dt);e.acid=Math.max(0,e.acid-dt);e.revealed=Math.max(0,e.revealed-dt);if(e.tags.includes("regen")&&e.burn<=0&&e.acid<=0)e.hp=Math.min(e.max,e.hp+dt*(1.5+garden.wave*.05));if(e.burn>0)e.hp-=dt*(7+garden.wave*.1);if(e.acid>0)e.hp-=dt*(5+garden.wave*.08);if(e.stun>0)return;const sp=e.speed*(e.slow>0?.48:1);e.prog+=sp*dt/GT;while(e.prog>=1&&!e.reached){e.prog--;e.seg++;if(e.seg>=garden.route.length-1){e.reached=true;return}}const a=gardenCenter(garden.route[e.seg]),b=gardenCenter(garden.route[Math.min(e.seg+1,garden.route.length-1)]);e.x=a.x+(b.x-a.x)*e.prog;e.y=a.y+(b.y-a.y)*e.prog}
  function updateGTower(tw,dt){tw.cool-=dt;if(tw.cool>0)return;const tool=tools[tw.type];let range=tool.range;if(garden.jam.has(key(tw.x,tw.y)))range*=.68;let list=garden.enemies.filter(e=>Math.hypot(e.x-(tw.x*GT+GT/2),e.y-(tw.y*GT+GT/2))<=range&&(!e.tags.includes("stealth")||e.revealed>0||tw.type==="beacon"));list.sort((a,b)=>(b.seg+b.prog)-(a.seg+a.prog));const e=list[0];if(!e)return;tw.cool=tool.rate;let dmg=tool.dmg;if(tw.type==="frost"){e.slow=1.8;if(e.tags.includes("fast")||e.tags.includes("flying"))dmg*=1.7}if(tw.type==="rail"&&(e.tags.includes("armored")||e.tags.includes("shielded")))dmg*=1.85;if(tw.type==="acid"){e.acid=2.4;if(e.tags.includes("armored")||e.tags.includes("regen"))dmg*=2.1}if(tw.type==="beacon"){e.revealed=3;if(e.tags.includes("stealth")||e.tags.includes("flying"))dmg*=2.2}damageG(e,dmg,tw.type);garden.shots.push({x:tw.x*GT+GT/2,y:tw.y*GT+GT/2,tx:e.x,ty:e.y,life:.12,color:tool.color})}
  function updateGTrap(tr,dt){tr.cool=Math.max(0,tr.cool-dt);if(tr.cool>0)return;const c=gardenCenter(tr),tool=tools[tr.type];for(const e of garden.enemies){if(Math.hypot(e.x-c.x,e.y-c.y)>18)continue;if(e.tags.includes("flying")&&!['emp','flame'].includes(tr.type))continue;if(tr.type==="tar"){e.slow=2.5;tr.cool=2.4}if(tr.type==="spikes"){damageG(e,28+garden.wave*.28,"spikes");tr.cool=1.1}if(tr.type==="emp"){e.stun=1.15;e.revealed=4;e.shield=Math.max(0,e.shield-90-garden.wave*2);damageG(e,38,"emp");tr.cool=3.2}if(tr.type==="flame"){e.burn=3;damageG(e,e.tags.includes("regen")?42:18,"flame");tr.cool=2.2}if(tr.type==="crusher"){damageG(e,e.tags.includes("armored")||e.mini||e.boss?95:40,"crusher");e.stun=.45;tr.cool=4.2}garden.shots.push({x:c.x,y:c.y,tx:e.x,ty:e.y,life:.16,color:tool.color});break}}
  function damageG(e,dmg,source){let f=dmg;if(e.tags.includes("armored")&&!['acid','rail','crusher'].includes(source))f*=.52;if(e.tags.includes("stealth")&&source!=="beacon"&&e.revealed<=0)f*=.35;if(e.shield>0&&!["emp","rail"].includes(source)){const used=Math.min(e.shield,f*.7);e.shield-=used;f-=used*.35}else if(e.shield>0){const used=Math.min(e.shield,f);e.shield-=used;f*=1.15}e.hp-=Math.max(1,f)}
  function clearGWave(){garden.running=false;const w=garden.wave;garden.money+=30+Math.floor(w*1.2);if(w>=20&&!areaUnlocked[1]){areaUnlocked[1]=true;msgG("Area 2 unlocked: Flood Grid.")}else if(w>=50&&!areaUnlocked[2]){areaUnlocked[2]=true;msgG("Area 3 unlocked: Blackout Core.")}else msgG(`Wave ${w} cleared.`);if(w===100&&!garden.bossOffered){garden.bossOffered=true;$("#gardenBossChoice").classList.remove("hidden");msgG("Wave 100 boss defeated. Return to menu or keep going.")}else garden.wave++;updateGardenButtons();updateGardenHud();drawGarden()}
  function msgG(s){$("#gardenMsg").textContent=s}function updateGardenHud(){if(!garden)return;$("#gardenArea").textContent=garden.area;$("#gardenWave").textContent=garden.wave;$("#gardenMoney").textContent=Math.floor(garden.money);$("#gardenCore").textContent=garden.core;$("#gardenKills").textContent=garden.kills;$("#gardenPath").textContent=garden.pathReady?"Ready":"Open"}
  function updateGardenButtons(){$$('[data-garden-area]').forEach(b=>{const a=Number(b.dataset.gardenArea);b.disabled=!areaUnlocked[a-1]||garden?.running;b.classList.toggle("active",a===selectedArea)})}
  function drawGarden(){if(!garden)return;g.clearRect(0,0,gC.width,gC.height);g.fillStyle="#050713";g.fillRect(0,0,gC.width,gC.height);for(let y=0;y<GR;y++)for(let x=0;x<GC;x++){const k=key(x,y),dug=garden.dug.has(k),water=garden.water.has(k),jam=garden.jam.has(k);if(water)drawWater(x,y);else if(dug)drawDug(x,y,jam);else drawBlock(x,y,jam)}if(garden.route.length>2){g.strokeStyle="rgba(255,255,255,.16)";g.lineWidth=5;g.beginPath();garden.route.forEach((p,i)=>{const c=gardenCenter(p);if(i)g.lineTo(c.x,c.y);else g.moveTo(c.x,c.y)});g.stroke()}if(!garden.running&&selectedTool==="dig"&&!garden.pathReady){validNextTiles().forEach(drawNext);drawEndpoint(endpoint())}drawSpawn();drawBase();garden.traps.forEach(drawTrap);garden.towers.forEach(drawTower);garden.enemies.forEach(drawGEnemy);garden.shots.forEach(s=>{g.strokeStyle=s.color;g.lineWidth=3;g.beginPath();g.moveTo(s.x,s.y);g.lineTo(s.tx,s.ty);g.stroke()})}
  function rr(x,y,w,h,r,fill,stroke){g.beginPath();g.moveTo(x+r,y);g.arcTo(x+w,y,x+w,y+h,r);g.arcTo(x+w,y+h,x,y+h,r);g.arcTo(x,y+h,x,y,r);g.arcTo(x,y,x+w,y,r);if(fill)g.fill();if(stroke)g.stroke()}function drawBlock(x,y,j){g.fillStyle=j?"rgba(82,42,130,.72)":"rgba(38,42,69,.96)";rr(x*GT+3,y*GT+3,GT-6,GT-6,7,true,false);g.strokeStyle=j?"rgba(155,92,255,.42)":"rgba(255,255,255,.08)";g.strokeRect(x*GT+4.5,y*GT+4.5,GT-9,GT-9)}function drawDug(x,y,j){g.fillStyle=j?"rgba(90,62,130,.45)":"rgba(96,103,125,.55)";rr(x*GT+5,y*GT+5,GT-10,GT-10,8,true,false)}function drawWater(x,y){g.fillStyle="rgba(0,160,255,.28)";rr(x*GT+3,y*GT+3,GT-6,GT-6,7,true,false);g.strokeStyle="rgba(0,229,255,.55)";g.strokeRect(x*GT+7,y*GT+12,GT-14,GT-24)}function drawNext(p){g.strokeStyle=css("--accent");g.fillStyle="rgba(0,245,196,.14)";g.lineWidth=3;rr(p.x*GT+5,p.y*GT+5,GT-10,GT-10,8,true,true)}function drawEndpoint(p){g.strokeStyle=css("--warn");g.lineWidth=3;rr(p.x*GT+5,p.y*GT+5,GT-10,GT-10,8,false,true)}function drawSpawn(){const c=gardenCenter(SPAWN);g.fillStyle=css("--warn");g.beginPath();g.moveTo(c.x-12,c.y-13);g.lineTo(c.x+15,c.y);g.lineTo(c.x-12,c.y+13);g.closePath();g.fill()}function drawBase(){const c=gardenCenter(BASE);g.fillStyle=css("--good");g.beginPath();g.arc(c.x,c.y,16,0,Math.PI*2);g.fill()}function drawTower(t){const c=gardenCenter(t),tool=tools[t.type];g.strokeStyle=tool.color;g.fillStyle=tool.color;g.lineWidth=3;g.beginPath();g.arc(c.x,c.y,13,0,Math.PI*2);g.stroke();g.fillRect(c.x-4,c.y-4,8,8)}function drawTrap(t){const c=gardenCenter(t),tool=tools[t.type];g.fillStyle=tool.color;rr(c.x-13,c.y-13,26,26,5,true,false)}function drawGEnemy(e){g.fillStyle=e.color;g.beginPath();g.arc(e.x,e.y,e.boss?17:e.mini?14:10,0,Math.PI*2);g.fill();g.fillStyle=css("--bad");g.fillRect(e.x-16,e.y-20,32,4);g.fillStyle=css("--good");g.fillRect(e.x-16,e.y-20,32*clamp(e.hp/e.max,0,1),4);if(e.shield>0){g.fillStyle="#00e5ff";g.fillRect(e.x-16,e.y-25,32*clamp(e.shield/(e.max*.3),0,1),3)}}
  $$("[data-garden-tool]").forEach(b=>b.addEventListener("click",()=>{selectedTool=b.dataset.gardenTool;$("#gardenMsg").textContent=selectedTool==="dig"?"Click one highlighted block at the front of the path. Only the endpoint can extend.":"Selected build tool. Towers off path, traps on path."}));$$('[data-garden-area]').forEach(b=>b.addEventListener("click",()=>{const a=Number(b.dataset.gardenArea);if(!areaUnlocked[a-1]){msgG(`Area ${a} is locked.`);return}if(garden?.running)return;selectedArea=a;resetGarden()}));gC.addEventListener("click",e=>{const r=gC.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*(gC.width/r.width)/GT),y=Math.floor((e.clientY-r.top)*(gC.height/r.height)/GT);placeGarden(x,y)});$("#gardenStartBtn").addEventListener("click",startGarden);$("#gardenResetBtn").addEventListener("click",resetGarden);$("#gardenMenuBtn").addEventListener("click",()=>showSection("home"));$("#gardenEndlessBtn").addEventListener("click",()=>{garden.wave=101;garden.endless=true;$("#gardenBossChoice").classList.add("hidden");updateGardenHud();msgG("Endless mode active.")});

  resetVoid(); resetRune(); resetMaze(); resetGarden(); showGame("void"); showSection("home");
});
